services:
  postgres:
    image: postgres:18-alpine
    container_name: justinus-api-postgres
    environment:
      POSTGRES_DB: justinus
      POSTGRES_USER: justinus
      POSTGRES_PASSWORD: justinus
    ports:
      - "5432:5432"
    volumes:
      - justinus-api-postgres-data:/var/lib/postgresql

volumes:
  justinus-api-postgres-data:
