spring:
  application:
    name: justinus-api
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:justinus}
    username: ${POSTGRES_USER:justinus}
    password: ${POSTGRES_PASSWORD:justinus}
  flyway:
    locations: classpath:db/migration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
