spring:
  application:
    name: justinus-api
  datasource:
    url: jdbc:postgresql://localhost:5432/justinus
    username: justinus
    password: justinus
  flyway:
    locations: classpath:db/migration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
